### PR TITLE
Fix style location for APPROVE / EDIT / DELETE buttons

### PR DESCRIPTION
**Pull request by Galixte**
@AlexSheer could you merge this, please?

### CODE REVIEW

**Comment by Galixte** [comment]
With this PR the displaying is fixed:
2017-10-18 05_04_18- 1 forum de tests - base de connaissances categorie - opera

**Comment by Galixte** [comment]
With default values for username max length setting:
username_length_setting

There is a problem of displaying for long usernames, like this problem:
username_length

This PR fix this.

**Comment by AlexSheer** [comment]
Look at now https://sheer.phpbbguru.net/phpbb321/knowledgebase/category?id=1
Like elegancy

**Comment by Galixte** [comment]
@AlexSheer, yes it's better. Thanks for considering my proposed changes. ;)

**Pull request closed without merging**
