### PR TITLE
Fix style

### PR DESCRIPTION
**Pull request by Galixte**
Hi @AlexSheer,

could you merge this, please?

Before:
before fix style cat

After:
after fix style cat

### CODE REVIEW

**Comment by Galixte** [comment]
@AlexSheer you have reverted my changes https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/commit/703c80497333b54c8a93b1487df9d3dbf1ef4fb1, see now the problem:


2017-10-17 23_37_07-forum de tests - base de connaissances categorie - opera

**Comment by AlexSheer** [comment]
I dont know why
Try it at https://sheer.phpbbguru.net/phpbb321/index.php
Login: Galixte
Passw:  knowledgebase

**Comment by Galixte** [comment]
I can’t see this problem on your online board because, and as you can see in my screenshot, this problem of style appears only for users which have permissions to delete/edit articles.

**Comment by AlexSheer** [comment]
No saw any problems
2017-10-18 03 17 17-fullpage
2017-10-18 03 17 00-fullpage

**Comment by Galixte** [comment]
I can’t believe that we have the same CSS, my screenshots have the same displaying on Chrome & Firefox.

Fixed here: https://github.com/AlexSheer/phpbb3.2-Knowledge-Base/pull/13.

**Pull request merged**
